### ISSUE TITLE
Add block height to TransactionResult struct

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-go-sdk#307]
The Access API now includes a `block_height` field in the transaction result response: https://github.com/onflow/flow-go/pull/2514/files#diff-d3c4be8def31760d695c22242edd5c0ac54e470cb9b4c419bf25fa0ed243706f

The Go SDK should be updated to include this field in the gRPC and HTTP client responses. Specifically, the `TransactionResult` struct should be updated to include a `BlockHeight` field.

cc @emilic

**Comment by emilic** [comment]
I will attempt to make a PR for this.

**Comment by emilic** [comment]
Another note: https://raw.githubusercontent.com/onflow/flow/master/openapi/access.yaml hasn't been updated to contain the block height in the schema:
```
    TransactionResult:
      type: object
      required:
        - block_id
        - status
        - status_code
        - error_message
        - computation_used
        - events
```
